### ISSUE TITLE
Error when running under python3

### ISSUE THREAD

**Issue by jigarmistry** [Stumblinbear/Prism#3]
`python3 bin/prism-panel`

```
  File "bin/prism-panel", line 40, in <module>
    sys.exit(daemon.start(sys.argv))
  File "/Users/tosc174/Downloads/Prism-master/prism/daemon.py", line 27, in start
    prism.settings.init(os.getpid())
  File "/Users/tosc174/Downloads/Prism-master/prism/settings.py", line 132, in init
    prism_login.create_user(username, password, username.capitalize(), 'Main Administrator', ['*'])
NameError: name 'prism_login' is not defined
```

**Comment by FFX01** [comment]
It appears that the variable `prism_login` isn't declared int the scope of the `init` function here https://github.com/Stumblinbear/Prism/blob/master/prism/settings.py#L132.

I do see this line in the `post_init` function:

``` python
import prism.login as prism_login
```

But, I assume that function isn't called until after the `init` function judging by it's name. 

I think the best way to fix this is to import the `User` class from `prism/login.py` and refactor the `create_user` function to instead be a class method of the `User` class.

That said, I just stumbled upon this repo, so there may be a reason this function is structured this way.

@Stumblinbear 
What do you think? Am I off the mark here?

**Comment by Stumblinbear** [comment]
Odd, because it should ONLY work under python 3? I'll look into it.

(( I realize that I haven't tested a fresh install in a while. I'll do that, now ))

_Edit: Fixed :v (Was initially unaware you could close issues via commits, but it's fixed. Learn somethin new every day)_

**Comment by FFX01** [comment]
> Edit: Fixed :v (Was initially unaware you could close issues via commits, but it's fixed. Learn somethin new every day)

Yep! Just put resolve #5 or whatever in the commit message and you're good to go. I find it's usually better to make a branch for each issue and close the issue with a pull request. That way it's more clear exactly which changes were made to fix the issue. That's just my way of doing it.

**Comment by Stumblinbear** [comment]
Thanks for the info, though git is... Not yet my strong point. I'll figure it out as I go along :3
